# Generated by Django 5.0.1 on 2024-04-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.TextField()),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('writetime', models.TextField(default="datetime('now', 'localtime')")),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
