# Generated by Django 5.0.1 on 2024-04-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_post_writetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posId', models.IntegerField()),
                ('writer', models.TextField()),
                ('content', models.TextField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
