# Generated by Django 5.0.1 on 2024-04-27 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='posId',
            new_name='postId',
        ),
    ]
