# Generated by Django 5.0.1 on 2024-04-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_rename_posid_comments_postid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.IntegerField()),
                ('writer', models.TextField()),
                ('content', models.TextField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
