# Generated by Django 5.0.1 on 2024-05-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_comment_delete_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.TextField(max_length=30),
        ),
    ]
